// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrrlwitirlyeszptxdcu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJycmx3aXRpcmx5ZXN6cHR4ZGN1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkwNDQzNzMsImV4cCI6MjA2NDYyMDM3M30.oyyC8tmgmaNxgNNQFInCWa8d_D02U0sLnEEr3b-h4Ak";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);